// ══════════════════════════════════════════════════════════════════════════════
// lidiaCatalogue.mjs — fiches d'exercices à ajouter à la médiathèque (table
// `exercises_catalogue`) si elles n'y sont pas déjà (comparaison sur `nom`,
// insensible à la casse). Colonnes : nom, categorie, positionnement, execution,
// respiration, vigilance, media_url (photo laissée vide, à charger à la main).
// ══════════════════════════════════════════════════════════════════════════════

export const CATALOGUE = [
  {
    nom: "Kas glute bridge",
    categorie: "Musculation avec charges",
    positionnement: "Omoplates au sol (ou appuyées sur un step bas), barre ou charge sur le pli des hanches, pieds à plat proches des fessiers, bassin en rétroversion.",
    execution: "Monter le bassin sur une amplitude courte (les 15 à 20 derniers degrés seulement), en gardant les tibias verticaux et la rétroversion. Serrer fort les fessiers en haut, redescendre à peine. Le bas du dos ne travaille pas.",
    respiration: "Expiration à la montée, inspiration en position basse.",
    vigilance: "Amplitude volontairement réduite : c'est un exercice de contraction du grand fessier, pas un pont complet. Ne jamais cambrer, menton rentré.",
  },
  {
    nom: "Abduction à la machine (buste penché)",
    categorie: "Machines guidées (salle de sport)",
    positionnement: "Assise sur la machine à abduction, dos décollé du dossier, buste incliné vers l'avant (30 à 45°), mains sur les poignées ou les cuisses.",
    execution: "Écarter les cuisses contre la résistance jusqu'à l'amplitude complète, marquer un temps d'arrêt d'une seconde en position ouverte, revenir en contrôlant sans relâcher la tension.",
    respiration: "Expiration pendant l'ouverture, inspiration au retour.",
    vigilance: "Le buste penché en avant oriente le travail vers le haut du grand fessier. Pas d'élan du dos, pas de à-coups ; garder les pieds et genoux alignés.",
  },
  {
    nom: "Abduction assise à la machine",
    categorie: "Machines guidées (salle de sport)",
    positionnement: "Assise bien calée au fond de la machine, dos contre le dossier, chevilles/genoux contre les coussinets.",
    execution: "Écarter les cuisses jusqu'à l'amplitude maximale confortable, tenir une seconde, revenir lentement en gardant une tension constante.",
    respiration: "Expiration à l'ouverture, inspiration au retour.",
    vigilance: "Ne pas s'aider en poussant sur les bras ou en creusant le dos. Mouvement contrôlé sur toute l'amplitude, sans claquer les plaques.",
  },
  {
    nom: "Adduction à la machine",
    categorie: "Machines guidées (salle de sport)",
    positionnement: "Assise au fond de la machine, dos contre le dossier, cuisses écartées, coussinets contre l'intérieur des genoux.",
    execution: "Rapprocher les cuisses contre la résistance jusqu'à ce qu'elles se touchent presque, tenir une seconde, revenir en contrôlant l'écartement.",
    respiration: "Expiration au rapprochement, inspiration à l'ouverture.",
    vigilance: "Amplitude d'ouverture adaptée à ta souplesse, sans forcer l'étirement. Sert d'équilibre aux abducteurs pour stabiliser bassin et genou.",
  },
  {
    nom: "Leg curl allongé",
    categorie: "Machines guidées (salle de sport)",
    positionnement: "Allongée sur le ventre sur la machine, genoux juste au-delà du bord du banc, chevilles sous le rouleau, hanches plaquées.",
    execution: "Fléchir les genoux pour amener les talons vers les fessiers, contracter les ischio-jambiers en fin de course, revenir en contrôlant l'excentrique sur 3 secondes.",
    respiration: "Expiration pendant la flexion, inspiration pendant le retour.",
    vigilance: "Ne pas décoller le bassin du banc (signe de charge trop lourde). Mouvement complet, sans à-coups ni rebond en bas.",
  },
  {
    nom: "Leg curl assis",
    categorie: "Machines guidées (salle de sport)",
    positionnement: "Assise, dos calé contre le dossier, coussin de cuisse verrouillé, arrière des chevilles sur le rouleau, jambes tendues.",
    execution: "Fléchir les genoux vers le sol jusqu'à l'amplitude maximale, marquer une seconde de contraction, remonter en contrôlant sur 3 secondes.",
    respiration: "Expiration pendant la flexion, inspiration au retour.",
    vigilance: "Garder le bassin et le haut du corps immobiles ; le mouvement vient uniquement des genoux. Régler la machine à ta longueur de jambe.",
  },
  {
    nom: "Extension du dos à 45° (biais fessier)",
    categorie: "Poids du corps",
    positionnement: "Banc à lombaires réglé à 45°, appui sur le haut des cuisses (pas sur le bassin), pieds calés, pointes de pieds légèrement vers l'extérieur. Charge éventuelle tenue contre la poitrine.",
    execution: "Partir buste vers le bas, bassin en rétroversion et dos légèrement enroulé (pas cambré), remonter par extension des HANCHES et s'arrêter à l'alignement — sans partir en hyperextension lombaire. Serrer les fessiers en haut.",
    respiration: "Expiration à la remontée, inspiration à la descente.",
    vigilance: "C'est un hip extension à biais fessier, pas un back extension : on garde le dos rond-neutre et on pousse avec les fessiers. Aucune hyperextension du bas du dos en fin de course.",
  },
  {
    nom: "Pull-through à la poulie",
    categorie: "Musculation avec charges",
    positionnement: "Dos à la poulie basse, corde passée entre les jambes, deux à trois pas en avant pour mettre le câble en tension, pieds largeur bassin, genoux peu fléchis.",
    execution: "Pousser les hanches vers l'arrière en gardant le dos neutre (le câble tire les mains entre les cuisses), puis revenir debout par extension des hanches en serrant les fessiers. Les bras restent passifs.",
    respiration: "Inspiration pendant le recul des hanches, expiration à l'extension.",
    vigilance: "Le mouvement part des hanches, pas des bras ni du bas du dos. Garder les abdos gainés, ne pas arrondir la colonne.",
  },
  {
    nom: "Hip thrust unilatéral",
    categorie: "Poids du corps",
    positionnement: "Haut du dos appuyé sur un banc, une jambe au sol pied à plat sous le genou, l'autre jambe tendue ou genou ramené vers la poitrine. Charge éventuelle sur la hanche.",
    execution: "Pousser dans le talon de la jambe d'appui pour monter le bassin jusqu'à l'alignement genou-hanche-épaule, contracter le fessier en haut, redescendre en contrôlant.",
    respiration: "Expiration à la poussée, inspiration à la descente.",
    vigilance: "Le bassin reste strictement horizontal (pas de bascule ni de rotation d'un côté). Amplitude complète mais sans cambrer le bas du dos.",
  },
  {
    nom: "Hip thrust à la machine",
    categorie: "Machines guidées (salle de sport)",
    positionnement: "Installée dans la machine à hip thrust, ceinture ou coussin sur le pli des hanches, dos calé, pieds à plat largeur bassin.",
    execution: "Pousser dans les talons pour étendre les hanches jusqu'au verrouillage, marquer un temps en haut, redescendre en contrôlant sur un tempo régulier sans relâcher complètement en bas.",
    respiration: "Expiration puissante à la poussée, inspiration à la descente.",
    vigilance: "Chercher la contraction des fessiers, pas le rebond. Menton rentré, côtes basses, pas d'hyperextension lombaire en haut.",
  },
  {
    nom: "Step-up en B-stance (kickstand)",
    categorie: "Poids du corps",
    positionnement: "Face à un step bas (20 à 30 cm), un pied à plat dessus (jambe motrice), l'autre pied au sol légèrement en arrière servant seulement d'appui léger (~20 % du poids). Haltères le long du corps en option.",
    execution: "Buste penché vers l'avant, pousser dans le talon de la jambe sur le step pour monter — le fessier fait le travail, la jambe arrière reste quasi passive. Redescendre en contrôlant.",
    respiration: "Expiration à la montée, inspiration à la descente.",
    vigilance: "Box volontairement bas et buste penché pour minimiser le quadriceps et cibler le fessier. Genou de la jambe motrice aligné avec le pied, pas de poussée franche de la jambe arrière.",
  },
  {
    nom: "Cable kickback (extension de hanche à la poulie)",
    categorie: "Musculation avec charges",
    positionnement: "Face à la poulie basse, sangle à la cheville, léger appui des mains sur le montant, buste incliné en avant, gainage abdominal actif.",
    execution: "Tendre la jambe vers l'arrière par extension de hanche pure jusqu'à la contraction du fessier, tenir une seconde, revenir en contrôlant sans relâcher la tension.",
    respiration: "Expiration pendant l'extension, inspiration au retour.",
    vigilance: "Ne pas cambrer le bas du dos pour aller plus loin : l'amplitude vient de la hanche. Bassin stable, mouvement lent.",
  },
  {
    nom: "Frog pump",
    categorie: "Poids du corps",
    positionnement: "Allongée sur le dos, plantes de pieds jointes et talons ramenés près du bassin, genoux ouverts vers l'extérieur (position grenouille).",
    execution: "Monter le bassin en poussant dans les tranches externes des pieds, serrer fort les fessiers en haut, redescendre à peine et enchaîner. Possibilité de petites pulsations en fin de série.",
    respiration: "Expiration à la montée, respiration courte sur les pulsations.",
    vigilance: "Exercice de congestion : amplitude courte, tension continue, on ne repose pas le bassin entre les répétitions. Pas de cambrure.",
  },
  {
    nom: "Poussée de traîneau (sled push)",
    categorie: "Fonctionnel",
    positionnement: "Mains sur les montants du traîneau bras tendus, buste penché à environ 45°, corps gainé en ligne, appuis sur l'avant des pieds.",
    execution: "Avancer par poussées puissantes des jambes et des hanches, petits pas rapides, en gardant les bras tendus et le tronc gainé sur toute la distance.",
    respiration: "Respiration rythmée avec les appuis, sans blocage prolongé.",
    vigilance: "Excellent pour les fessiers et le cardio avec très peu de courbatures (pas de phase excentrique). Garder le dos neutre, ne pas s'écrouler sur les bras.",
  },
  {
    nom: "Face pull",
    categorie: "Musculation avec charges",
    positionnement: "Face à une poulie réglée à hauteur de visage, corde tenue en pronation, un pied légèrement avancé, gainage actif.",
    execution: "Tirer la corde vers le visage en écartant les mains et en amenant les coudes hauts et vers l'arrière, rapprocher les omoplates, revenir en contrôlant.",
    respiration: "Expiration pendant le tirage, inspiration au retour.",
    vigilance: "Charge légère à modérée, c'est un exercice de santé d'épaule et de posture. Pas d'élan du buste, épaules basses.",
  },
  {
    nom: "Pallof press",
    categorie: "Fonctionnel",
    positionnement: "Debout de profil par rapport à une poulie (ou élastique) réglée à hauteur de poitrine, mains jointes sur la poignée contre le sternum, pieds largeur bassin, gainage actif.",
    execution: "Tendre les bras devant soi en résistant à la rotation qu'impose le câble, tenir une à deux secondes, revenir à la poitrine sans se laisser tourner.",
    respiration: "Expiration pendant l'extension des bras, respiration continue sur le maintien.",
    vigilance: "Anti-rotation : le buste et le bassin ne bougent pas. Ajuster la distance à la poulie pour doser la difficulté.",
  },
  {
    nom: "Relevé de genoux suspendu",
    categorie: "Poids du corps",
    positionnement: "Suspendue à une barre (ou appui avant-bras sur une station), corps gréé, épaules engagées, jambes tendues vers le bas.",
    execution: "Enrouler le bassin et monter les genoux vers la poitrine en contractant les abdominaux, marquer un temps en haut, redescendre lentement sans balancer.",
    respiration: "Expiration à la montée, inspiration à la descente.",
    vigilance: "Le mouvement vient de l'enroulement du bassin, pas d'un simple balancement des jambes. Contrôler la descente, éviter l'élan.",
  },
  {
    nom: "Vacuum abdominal",
    categorie: "Échauffement & Mobilité",
    positionnement: "Debout, assise ou à quatre pattes, colonne neutre, épaules relâchées. De préférence à jeun.",
    execution: "Expirer tout l'air des poumons, puis aspirer le ventre vers l'intérieur et vers le haut (sous les côtes) au maximum, maintenir 15 à 20 secondes en respirant superficiellement, relâcher. Répéter.",
    respiration: "Expiration complète avant l'aspiration, respiration courte pendant le maintien.",
    vigilance: "Travail du transverse : aucun à-coup, aucune apnée forcée longue. À éviter en cas de grossesse ou de reflux marqué.",
  },
  {
    nom: "Dead bug lesté",
    categorie: "Poids du corps",
    positionnement: "Allongée sur le dos, bras tendus vers le plafond (petit haltère ou disque en main), hanches et genoux fléchis à 90°, bas du dos plaqué au sol.",
    execution: "Descendre lentement le bras et la jambe opposés vers le sol sans décoller les lombaires, revenir, alterner. Gainage constant.",
    respiration: "Expiration pendant l'extension bras/jambe, inspiration au retour.",
    vigilance: "Le bas du dos reste collé au sol du début à la fin : si le dos se creuse, réduire l'amplitude. Mouvement lent et contrôlé.",
  },
  {
    nom: "Roue abdominale (ab wheel)",
    categorie: "Poids du corps",
    positionnement: "À genoux, roue tenue à deux mains sous les épaules, bassin en rétroversion, abdominaux gainés.",
    execution: "Rouler vers l'avant en allongeant le corps aussi loin que le gainage le permet sans cambrer, puis revenir en contractant les abdominaux. Réduire l'amplitude si besoin.",
    respiration: "Inspiration pendant la descente vers l'avant, expiration au retour.",
    vigilance: "Anti-extension : ne jamais laisser le bas du dos se creuser. Commencer avec une amplitude courte et l'augmenter progressivement.",
  },
  {
    nom: "Marche latérale élastique (band walk)",
    categorie: "Échauffement & Mobilité",
    positionnement: "Élastique autour des cuisses (au-dessus des genoux) ou des chevilles, léger quart de squat, pieds largeur bassin, tension déjà présente dans la bande.",
    execution: "Faire des pas latéraux en gardant la tension constante dans l'élastique, sans rapprocher complètement les pieds, sur quelques mètres dans un sens puis dans l'autre.",
    respiration: "Respiration régulière tout au long.",
    vigilance: "Garder les pieds parallèles et le bassin stable (pas de balancement). Le travail se sent sur le moyen fessier.",
  },
  {
    nom: "Monster walk",
    categorie: "Échauffement & Mobilité",
    positionnement: "Élastique autour des cuisses ou des chevilles, léger quart de squat, buste légèrement penché en avant.",
    execution: "Avancer par pas diagonaux (en canard), en écartant activement les cuisses contre l'élastique à chaque pas, puis reculer de la même façon.",
    respiration: "Respiration régulière.",
    vigilance: "Maintenir la tension de l'élastique en permanence, genoux qui ne rentrent pas vers l'intérieur, bassin stable.",
  },
  {
    nom: "Hip airplane",
    categorie: "Échauffement & Mobilité",
    positionnement: "En appui sur une jambe (légèrement fléchie), buste incliné vers l'avant en charnière de hanche, bras écartés, autre jambe tendue vers l'arrière dans le prolongement du tronc.",
    execution: "Ouvrir puis fermer le bassin lentement (rotation externe puis interne de la hanche d'appui) en gardant l'équilibre et l'alignement tronc-jambe libre.",
    respiration: "Respiration lente et contrôlée pendant les rotations.",
    vigilance: "Mouvement lent, amplitude maîtrisée. Travail d'équilibre et de contrôle du moyen fessier et des rotateurs de hanche ; se tenir à un support si besoin au début.",
  },
  {
    nom: "Tirage vertical à la poulie (prise neutre)",
    categorie: "Machines guidées (salle de sport)",
    positionnement: "Assise à la poulie haute, cuisses calées sous les coussinets, poignée en prise neutre (mains face à face), buste légèrement incliné en arrière, poitrine sortie.",
    execution: "Tirer la poignée vers le haut de la poitrine en amenant les coudes vers le bas et l'arrière, rapprocher les omoplates, revenir en contrôlant jusqu'à l'étirement complet.",
    respiration: "Expiration pendant le tirage, inspiration au retour.",
    vigilance: "Éviter de tirer en arrière avec tout le buste : le mouvement vient des dorsaux et des coudes. Pas de à-coups, amplitude complète.",
  },
  {
    nom: "Développé haltères incliné",
    categorie: "Musculation avec charges",
    positionnement: "Allongée sur un banc incliné à environ 30°, haltères au niveau des pectoraux hauts, poignets au-dessus des coudes, pieds ancrés au sol.",
    execution: "Pousser les haltères vers le haut jusqu'à extension des bras sans verrouiller brutalement, redescendre en contrôlant jusqu'à l'étirement raisonnable des pectoraux.",
    respiration: "Expiration pendant la poussée, inspiration à la descente.",
    vigilance: "Ne pas trop incliner le banc (au-delà de 30-40° le travail devient très épaule). Omoplates serrées et basses, pas de cambrure excessive.",
  },
  {
    nom: "Développé militaire haltères (assis)",
    categorie: "Musculation avec charges",
    positionnement: "Assise sur un banc avec dossier vertical, haltères au niveau des épaules paumes vers l'avant, gainage abdominal et fessier actif, pieds à plat.",
    execution: "Pousser les haltères à la verticale au-dessus de la tête jusqu'à l'extension des bras, redescendre de façon contrôlée au niveau des épaules.",
    respiration: "Inspiration et gainage avant la poussée, expiration en fin de mouvement.",
    vigilance: "Ne pas cambrer le bas du dos pour compenser : garder les côtes basses. Trajectoire proche de la tête, poignets solides.",
  },
  {
    nom: "Corde à sauter",
    categorie: "Fonctionnel",
    positionnement: "Debout, corde à la bonne longueur (poignées arrivant aux aisselles quand on marche sur le milieu), coudes près du corps, regard devant.",
    execution: "Sauts légers sur l'avant des pieds, rotation de la corde par les poignets, réception souple. Alterner phases de travail intense et récupération active selon les consignes.",
    respiration: "Respiration rythmée et régulière.",
    vigilance: "Sauts bas et souples pour préserver chevilles et genoux. Alternative équivalente : vélo ou rameur en intervalles.",
  },
];
